spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/WebLab2
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE